;; extractor.cljs - libextractor used by gnunet-web website
;; Copyright (C) 2014  David Barksdale <amatus@amatus.name>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

(ns gnunet-web.extractor)

(def format-unknown 0)
(def format-utf8 1)
(def format-data 2)
(def format-string 3) ; unknown character encoding

(def type-descriptions
  [["reserved" "reserved value, do not use"]
   ["mimetype" "mime type"]
   ["embedded filename" "filename that was embedded (not necessarily the current filename)"]
   ["comment" "comment about the content"]
   ["title" "title of the work"]
   ["book title" "title of the book containing the work"]
   ["book edition" "edition of the book (or book containing the work)"]
   ["book chapter" "chapter number"]
   ["journal name" "journal or magazine the work was published in"]
   ["journal volume" "volume of a journal or multi-volume book"]
   ["journal number" "number of a journal, magazine or tech-report"]
   ["page count" "total number of pages of the work"]
   ["page range" "page numbers of the publication in the respective journal or book"]
   ["author name" "name of the author(s)"]
   ["author email" "e-mail of the author(s)"]
   ["author institution" "institution the author worked for"]
   ["publisher" "name of the publisher"]
   ["publisher's address" "Address of the publisher (often only the city)"]
   ["publishing institution" "institution that was involved in the publishing, but not necessarily the publisher"]
   ["publication series" "series of books the book was published in"]
   ["publication type" "type of the tech-report"]
   ["publication year" "year of publication (or, if unpublished, the year of creation)"]
   ["publication month" "month of publication (or, if unpublished, the month of creation)"]
   ["publication day" "day of publication (or, if unpublished, the day of creation relative to the given month"]
   ["publication date" "date of publication (or, if unpublished, the date of creation)"]
   ["bibtex eprint" "specification of an electronic publication"]
   ["bibtex entry type" "type of the publication for bibTeX bibliographies"]
   ["language" "language the work uses"]
   ["creation time" "time and date of creation"]
   ["URL" "universal resource location (where the work is made available)"]
   ["URI" "universal resource identifier"]
   ["international standard recording code" "ISRC number identifying the work"]
   ["MD4" "MD4 hash"]
   ["MD5" "MD5 hash"]
   ["SHA-0" "SHA-0 hash"]
   ["SHA-1" "SHA-1 hash"]
   ["RipeMD160" "RipeMD150 hash"]
   ["GPS latitude ref" "GPS latitude ref"]
   ["GPS latitude" "GPS latitude"]
   ["GPS longitude ref" "GPS longitude ref"]
   ["GPS longitude" "GPS longitude"]
   ["city" "name of the city where the document originated"]
   ["sublocation" "more specific location of the geographic origin"]
   ["country" "name of the country where the document originated"]
   ["country code" "ISO 2-letter country code for the country of origin"]
   ["unknown" "specifics are not known"]
   ["description" "description"]
   ["copyright" "Name of the entity holding the copyright"]
   ["rights" "information about rights"]
   ["keywords" "keywords"]
   ["abstract" "abstract"]
   ["summary" "summary"]
   ["subject" "subject matter"]
   ["creator" "name of the person who created the document"]
   ["format" "name of the document format"]
   ["format version" "version of the document format"]
   ["created by software" "name of the software that created the document"]
   ["unknown date" "ambiguous date (could specify creation time, modification time or access time)"]
   ["creation date" "date the document was created"]
   ["modification date" "date the document was modified"]
   ["last printed" "date the document was last printed"]
   ["last saved by" "name of the user who saved the document last"]
   ["total editing time" "time spent editing the document"]
   ["editing cycles" "number of editing cycles"]
   ["modified by software" "name of software making modifications"]
   ["revision history" "information about the revision history"]
   ["embedded file size" "size of the contents of the container as embedded in the file"]
   ["file type" "standard Macintosh Finder file type information"]
   ["creator" "standard Macintosh Finder file creator information"]
   ["package name" "unique identifier for the package"]
   ["package version" "version of the software and its package"]
   ["section" "category the software package belongs to"]
   ["upload priority" "priority for promoting the release to production"]
   ["dependencies" "packages this package depends upon"]
   ["conflicting packages" "packages that cannot be installed with this package"]
   ["replaced packages" "packages made obsolete by this package"]
   ["provides" "functionality provided by this package"]
   ["recommendations" "packages recommended for installation in conjunction with this package"]
   ["suggestions" "packages suggested for installation in conjunction with this package"]
   ["maintainer" "name of the maintainer"]
   ["installed size" "space consumption after installation"]
   ["source" "original source code"]
   ["is essential" "package is marked as essential"]
   ["target architecture" "hardware architecture the contents can be used for"]
   ["pre-dependency" "dependency that must be satisfied before installation"]
   ["license" "applicable copyright license"]
   ["distribution" "distribution the package is a part of"]
   ["build host" "machine the package was build on"]
   ["vendor" "name of the software vendor"]
   ["target operating system" "operating system for which this package was made"]
   ["software version" "version of the software contained in the file"]
   ["target platform" "name of the architecture, operating system and distribution this package is for"]
   ["resource type" "categorization of the nature of the resource that is more specific than the file format"]
   ["library search path" "path in the file system to be considered when looking for required libraries"]
   ["library dependency" "name of a library that this file depends on"]
   ["camera make" "camera make"]
   ["camera model" "camera model"]
   ["exposure" "exposure"]
   ["aperture" "aperture"]
   ["exposure bias" "exposure bias"]
   ["flash" "flash"]
   ["flash bias" "flash bias"]
   ["focal length" "focal length"]
   ["focal length 35mm" "focal length 35mm"]
   ["iso speed" "iso speed"]
   ["exposure mode" "exposure mode"]
   ["metering mode" "metering mode"]
   ["macro mode" "macro mode"]
   ["image quality" "image quality"]
   ["white balance" "white balance"]
   ["orientation" "orientation"]
   ["magnification" "magnification"]
   ["image dimensions" "size of the image in pixels (width times height)"]
   ["produced by software" "produced by software"]
   ["thumbnail" "smaller version of the image for previewing"]
   ["image resolution" "resolution in dots per inch"]
   ["source" "Originating entity"]
   ["character set" "character encoding used"]
   ["line count" "number of lines"]
   ["paragraph count" "number of paragraphs"]
   ["word count" "number of words"]
   ["character count" "number of characters"]
   ["page orientation" "page orientation"]
   ["paper size" "paper size"]
   ["template" "template the document uses or is based on"]
   ["company" "company"]
   ["manager" "manager"]
   ["revision number" "revision number"]
   ["duration" "play time for the medium"]
   ["album" "name of the album"]
   ["artist" "name of the artist or band"]
   ["genre" "genre"]
   ["track number" "original number of the track on the distribution medium"]
   ["disk number" "number of the disk in a multi-disk (or volume) distribution"]
   ["performer" "The artist(s) who performed the work (conductor, orchestra, soloists, actor, etc.)"]
   ["contact" "Contact information for the creator or distributor"]
   ["song version" "name of the version of the song (i.e. remix information)"]
   ["picture" "associated misc. picture"]
   ["cover picture" "picture of the cover of the distribution medium"]
   ["contributor picture" "picture of one of the contributors"]
   ["event picture" "picture of an associated event"]
   ["logo" "logo of an associated organization"]
   ["broadcast television system" "name of the television system for which the data is coded"]
   ["source device" "device used to create the object"]
   ["disclaimer" "legal disclaimer"]
   ["warning" "warning about the nature of the content"]
   ["page order" "order of the pages"]
   ["writer" "contributing writer"]
   ["product version" "product version"]
   ["contributor" "name of a contributor"]
   ["movie director" "name of the director"]
   ["network" "name of the broadcasting network or station"]
   ["show" "name of the show"]
   ["chapter name" "name of the chapter"]
   ["song count" "number of songs"]
   ["starting song" "number of the first song to play"]
   ["play counter" "number of times the media has been played"]
   ["conductor" "name of the conductor"]
   ["interpretation" "information about the people behind interpretations of an existing piece"]
   ["composer" "name of the composer"]
   ["beats per minute" "beats per minute"]
   ["encoded by" "name of person or organization that encoded the file"]
   ["original title" "title of the original work"]
   ["original artist" "name of the original artist"]
   ["original writer" "name of the original lyricist or writer"]
   ["original release year" "year of the original release"]
   ["original performer" "name of the original performer"]
   ["lyrics" "lyrics of the song or text description of vocal activities"]
   ["popularity" "information about the file's popularity"]
   ["licensee" "name of the owner or licensee of the file"]
   ["musician credit list" "names of contributing musicians"]
   ["mood" "keywords reflecting the mood of the piece"]
   ["subtitle" "subtitle of this part"]
   ["display type" "what rendering method should be used to display this item"]
   ["full data" "entry that contains the full, original binary data (not really meta data)"]
   ["rating" "rating of the content"]
   ["organization" "organization"]
   ["ripper" "ripper"]
   ["producer" "producer"]
   ["group" "name of the group or band"]
   ["original filename" "name of the original file (reserved for GNUnet)"]
   ["disc count" "count of discs inside collection this disc belongs to"]
   ["codec" "codec the data is stored in"]
   ["video codec" "codec the video data is stored in"]
   ["audio codec" "codec the audio data is stored in"]
   ["subtitle codec" "codec/format the subtitle data is stored in"]
   ["container format" "container format the data is stored in"]
   ["bitrate" "exact or average bitrate in bits/s"]
   ["nominal bitrate" "nominal bitrate in bits/s. The actual bitrate might be different from this target bitrate."]
   ["minimum bitrate" "minimum bitrate in bits/s"]
   ["maximum bitrate" "maximum bitrate in bits/s"]
   ["serial" "serial number of track"]
   ["encoder" "encoder used to encode this stream"]
   ["encoder version" "version of the encoder used to encode this stream"]
   ["track gain" "track gain in db"]
   ["track peak" "peak of the track"]
   ["album gain" "album gain in db"]
   ["album peak" "peak of the album"]
   ["reference level" "reference level of track and album gain values"]
   ["location name" "human readable descriptive location of where the media has been recorded or produced"]
   ["location elevation" "geo elevation of where the media has been recorded or produced in meters according to WGS84 (zero is average sea level)"]
   ["location horizontal error" "represents the expected error on the horizontal positioning in meters"]
   ["location movement speed" "speed of the capturing device when performing the capture. Represented in m/s"]
   ["location movement direction" "indicates the movement direction of the device performing the capture of a media. It is represented as degrees in floating point representation, 0 means the geographic north, and increases clockwise"]
   ["location capture direction" "indicates the direction the device is pointing to when capturing a media. It is represented as degrees in floating point representation, 0 means the geographic north, and increases clockwise"]
   ["show episode number" "number of the episode within a season/show"]
   ["show season number" "number of the season of a show/series"]
   ["grouping" "groups together media that are related and spans multiple tracks. An example are multiple pieces of a concerto"]
   ["device manufacturer" "manufacturer of the device used to create the media"]
   ["device model" "model of the device used to create the media"]
   ["audio language" "language of the audio track"]
   ["channels" "number of audio channels"]
   ["sample rate" "sample rate of the audio track"]
   ["audio depth" "number of bits per audio sample"]
   ["audio bitrate" "bitrate of the audio track"]
   ["maximum audio bitrate" "maximum audio bitrate"]
   ["video dimensions" "width and height of the video track (WxH)"]
   ["video depth" "numbers of bits per pixel"]
   ["frame rate" "number of frames per second (as D/N or floating point)"]
   ["pixel aspect ratio" "pixel aspect ratio (as D/N)"]
   ["video bitrate" "video bitrate"]
   ["maximum video bitrate" "maximum video bitrate"]
   ["subtitle language" "language of the subtitle track"]
   ["video language" "language of the video track"]
   ["table of contents" "chapters, contents or bookmarks (in xml format)"]
   ["video duration" "duration of a video stream"]
   ["audio duration" "duration of an audio stream"]
   ["subtitle duration" "duration of a subtitle stream"]])
